import { test, expect } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';
import { loginTestData } from '../testData/loginTestData';

test.describe.only('Orange HRM Login Tests', () => {
    let loginPage: LoginPage;

    test.beforeEach(async ({ page }) => {
        await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
        loginPage = new LoginPage(page);
    });

    test('Valid Login Test', async () => {
        const testData = loginTestData["validLogin"];
        await loginPage.login(testData.username, testData.password);
        const dashboardTitle = await loginPage.getDashboardTitle();
        expect(dashboardTitle).toBe(testData.expectedResult);
    });

    test('Invalid Login Test generated by AI', async () => {
        const testData = loginTestData["invalidLogin"];
        await loginPage.login(testData.username, testData.password);
        const errorMessage = await loginPage.getErrorMessage();
        expect(errorMessage).toBe(testData.expectedResult);
        expect(await loginPage.isErrorMessageDisplayed()).toBeTruthy();
    });
});